spring:
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        consumer-in-0:
          destination: demo-topic
          group: demo-group
      kafka:
        binder:
          brokers:
          - localhost:9092
          consumer-properties:
            auto.offset.reset: earliest