services:
  kafka1:
    image: apache/kafka:latest
    container_name: kafka1
    working_dir: /opt/kafka/bin/
    env_file:
    - server.env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:8081
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:8081
    ports:
    - 8081:8081
  kafka2:
    image: apache/kafka:latest
    container_name: kafka2
    working_dir: /opt/kafka/bin/    
    env_file:
    - server.env
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:8082
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://localhost:8082
    ports:
    - 8082:8082 
  kafka3:
    image: apache/kafka:latest
    container_name: kafka3
    working_dir: /opt/kafka/bin/    
    env_file:
    - server.env
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:8083
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,EXTERNAL://localhost:8083
    ports:
    - 8083:8083