spring:
  cloud:
    function:
      definition: physicalConsumer
    stream:
      bindings:
        physicalConsumer-in-0:
          destination: physical-delivery
          group: physical-delivery-service
      kafka:
        binder:
          brokers:
          - localhost:9092
          consumer-properties:
            auto.offset.reset: earliest