spring:
  cloud:
    function:
      definition: deliveryProcessor
    stream:
      bindings:
        deliveryProcessor-in-0:
          destination: order-events
          group: delivery-processor
        digital-delivery-out:
          destination: digital-delivery
        fedex-delivery-out:
          destination: fedex-delivery
        usps-delivery-out:
          destination: usps-delivery
      kafka:
        binder:
          brokers:
          - localhost:9092
          consumer-properties:
            auto.offset.reset: earliest