spring:
  cloud:
    function:
      definition:
        consumer
    stream:
      bindings:
        consumer-in-0:
          destination: demo-topic 
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto-offset.reset: earliest   # read messages --from-beginning